### ISSUE TITLE
무들 강좌 제작

### ISSUE THREAD

**Issue by WoolSeo** [gshslatexintro/An-Introduction-to-LaTeX#3]
여기 자료를 바탕으로 bfstudy.net에 latex 오픈 강좌를 만들어보려합니다. 괜찮겠지요?

**Comment by seungwonpark** [comment]
이 레포지토리에 명시된 라이선스에 의하면 괜찮아 보입니다.
https://github.com/gshslatexintro/An-Introduction-to-LaTeX/blob/master/LICENSE
